#pragma once
// Generated by tools/design.py; do not hand-edit.
#define PIN_MIC_BCLK 4
#define PIN_MIC_WS 5
#define PIN_MIC_SD 6
#define PIN_LCD_BL 7
#define PIN_LCD_RST 8
#define PIN_LCD_DC 9
#define PIN_LCD_CS 10
#define PIN_LCD_MOSI 11
#define PIN_LCD_SCK 12
#define PIN_NEXT 13
#define PIN_PTT 14
#define PIN_AMP_SD 15
#define PIN_AMP_BCLK 16
#define PIN_AMP_WS 17
#define PIN_AMP_DIN 18
#define PIN_LED_DATA 21
#define PIN_REC_LED 47
