import {camera,project,clamp,cross,sub,normalize} from './math.js';
const meshShader=`struct U{matrix:mat4x4f,offset:vec4f,color:vec4f};@group(0) @binding(0) var<uniform> u:U;struct O{@builtin(position) p:vec4f,@location(0) n:vec3f,@location(1) world:vec3f};@vertex fn vs(@location(0) p:vec3f,@location(1) n:vec3f)->O{var o:O;let w=p+u.offset.xyz;o.p=u.matrix*vec4f(w,1);o.n=n;o.world=w;return o;}@fragment fn fs(o:O)->@location(0) vec4f{let n=normalize(o.n);let l=normalize(vec3f(-3,5,4));let diffuse=.24+.68*abs(dot(n,l));let rim=pow(1.-abs(n.z),3.);return vec4f(u.color.rgb*diffuse+vec3f(.10,.065,.18)*rim,u.color.a);}`;
export class OrbRenderer {
  constructor(canvas,onInfo){this.canvas=canvas;this.info=onInfo;this.params={yaw:0,pitch:0,zoom:1,glow:.75,art:true,split:false,view:0,activity:0};this.cad=false;this.explode=0;this.selected='';this.hidden=new Set();this.paused=matchMedia('(prefers-reduced-motion: reduce)').matches;this.frame=0;this.frames=0;this.disposed=false;this.last=0;this.fps=0;this.quality=1;this.meshes=[];this.observer=new ResizeObserver(()=>this.resize());this.observer.observe(canvas);this.installInput()}
  installInput(){let down=null;this.canvas.addEventListener('pointerdown',e=>{down={x:e.clientX,y:e.clientY};this.canvas.setPointerCapture(e.pointerId)});this.canvas.addEventListener('pointermove',e=>{if(!down)return;this.params.yaw+=(e.clientX-down.x)*.007;this.params.pitch=clamp(this.params.pitch+(e.clientY-down.y)*.0025,-.23,.72);down={x:e.clientX,y:e.clientY}});const end=()=>down=null;this.canvas.addEventListener('pointerup',end);this.canvas.addEventListener('pointercancel',end);this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.params.zoom=clamp(this.params.zoom*Math.exp(e.deltaY*.001),.55,1.8)},{passive:false});this.canvas.addEventListener('dblclick',()=>this.reset())}
  reset(){Object.assign(this.params,{yaw:0,pitch:0,zoom:1})}
  async init(){
    try{
      if(!navigator.gpu)throw new Error('WebGPU unavailable');const adapter=await navigator.gpu.requestAdapter({powerPreference:'high-performance'});if(!adapter)throw new Error('No WebGPU adapter');this.device=await adapter.requestDevice();this.device.lost.then(x=>{if(!this.disposed)this.fallback('WebGPU device lost: '+x.reason)});this.device.addEventListener('uncapturederror',e=>{console.error(e.error.message);this.info({renderer:'WebGPU error',detail:e.error.message})});
      this.context=this.canvas.getContext('webgpu');this.format=navigator.gpu.getPreferredCanvasFormat();this.context.configure({device:this.device,format:this.format,alphaMode:'opaque'});
      const code=await (await fetch(new URL('./orb.wgsl',import.meta.url))).text(),module=this.device.createShaderModule({label:'CrystalBall glass and nebula',code});const compile=await module.getCompilationInfo();const errors=compile.messages.filter(x=>x.type==='error');if(errors.length)throw new Error(errors.map(x=>x.message).join('\n'));
      this.pipeline=await this.device.createRenderPipelineAsync({layout:'auto',vertex:{module,entryPoint:'vs'},fragment:{module,entryPoint:'fs',targets:[{format:this.format}]},primitive:{topology:'triangle-list'}});
      this.uniform=this.device.createBuffer({size:64,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});this.bind=this.device.createBindGroup({layout:this.pipeline.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:this.uniform}}]});this.kind='WebGPU';this.resize();this.info({renderer:'WebGPU',detail:adapter.info?.description||adapter.info?.device||'Native GPU pipeline'});
    }catch(error){this.fallback(error.message)}
    this.tick(performance.now());return this.kind;
  }
  fallback(reason){if(this.kind==='Canvas 2D')return;this.kind='Canvas 2D';if(this.context){this.context.unconfigure();const copy=this.canvas.cloneNode();this.canvas.replaceWith(copy);this.observer.unobserve(this.canvas);this.canvas=copy;this.observer.observe(copy);this.context=null;this.installInput()}this.ctx=this.canvas.getContext('2d');this.info({renderer:'Canvas 2D',detail:reason});this.resize()}
  resize(){this.drawnSignature='';const r=this.canvas.getBoundingClientRect();if(!r.width||!r.height)return;const ratio=Math.min(devicePixelRatio||1,1.5,1000/r.height)*this.quality;this.canvas.width=Math.round(r.width*ratio);this.canvas.height=Math.round(r.height*ratio);this.width=r.width;this.height=r.height;if(this.device&&this.kind==='WebGPU'){this.depth?.destroy();this.depth=this.device.createTexture({size:[this.canvas.width,this.canvas.height],format:'depth24plus',usage:GPUTextureUsage.RENDER_ATTACHMENT})}}
  tick(now){
    if(this.disposed)return;
    this.frame=requestAnimationFrame(t=>this.tick(t));
    if(document.hidden||this.gpuBusy)return;
    if(!this.paused)this.time=now*.001;
    // At most one submitted frame. Otherwise a CPU adapter accumulates an
    // unbounded GPU queue and screenshots, input and device shutdown stall.
    const signature=JSON.stringify([this.kind,this.canvas.width,this.canvas.height,this.params,
      this.cad,this.explode,this.selected,[...this.hidden],this.meshes.length]);
    if(this.paused&&signature===this.drawnSignature)return;
    this.drawnSignature=signature;
    const completed=()=>{
      const finish=performance.now(),dt=finish-(this.lastCompleted||finish-16);
      this.lastCompleted=finish;this.fps=this.fps?this.fps*.8+.2*1000/Math.max(1,dt):1000/Math.max(1,dt);
      this.info({fps:Math.round(this.fps)});this.gpuBusy=false;
      document.documentElement.dataset.gpuIdle='true';
    };
    try{
      if(this.kind==='WebGPU'){
        this.gpuBusy=true;document.documentElement.dataset.gpuIdle='false';
        if(this.cad&&this.meshes.length)this.drawCAD();else this.drawGPU();
        this.device.queue.onSubmittedWorkDone().then(completed,error=>{
          this.gpuBusy=false;if(!this.disposed)this.fallback(error.message);
        });
      }else{this.drawFallback();completed()}
    }catch(error){this.gpuBusy=false;this.fallback(error.message)}
  }
  drawGPU(){const p=this.params,v=new Float32Array([this.canvas.width,this.canvas.height,this.time||0,p.activity,p.yaw,p.pitch,p.zoom,p.glow,Number(p.art),Number(p.split),p.view,0]);this.device.queue.writeBuffer(this.uniform,0,v);const e=this.device.createCommandEncoder(),pass=e.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),clearValue:{r:0,g:0,b:0,a:1},loadOp:'clear',storeOp:'store'}]});pass.setPipeline(this.pipeline);pass.setBindGroup(0,this.bind);pass.draw(3);pass.end();this.device.queue.submit([e.finish()])}
  screenAnchor(){const split=this.params.split,w=this.width/(split?2:1),cam=camera(this.params.yaw,this.params.pitch,this.params.zoom,w/this.height);const p=project([0,1.87,.16],cam.matrix,w,this.height),a=project([-.45,1.87,.16],cam.matrix,w,this.height),b=project([.45,1.87,.16],cam.matrix,w,this.height);return {x:p[0],y:p[1],width:Math.abs(b[0]-a[0])*1.25,visible:!this.cad&&this.params.view===0&&Math.cos(this.params.yaw)>.45}}
  async loadCAD(){if(this.loadedCAD)return this.meshes.map(x=>x.name);if(this.kind!=='WebGPU')throw new Error('The exact CAD mesh viewer requires WebGPU. Beauty preview remains available.');const response=await fetch(new URL('../assets/assembly.json',import.meta.url));if(!response.ok)throw new Error('CAD asset is not installed. Run mechanical/model.py and copy the generated mesh JSON to web/assets/assembly.json.');const source=await response.json();const m=this.device.createShaderModule({code:meshShader});const descriptor={layout:'auto',vertex:{module:m,entryPoint:'vs',buffers:[{arrayStride:24,attributes:[{shaderLocation:0,offset:0,format:'float32x3'},{shaderLocation:1,offset:12,format:'float32x3'}]}]},fragment:{module:m,entryPoint:'fs',targets:[{format:this.format,blend:{color:{srcFactor:'src-alpha',dstFactor:'one-minus-src-alpha'},alpha:{srcFactor:'one',dstFactor:'one-minus-src-alpha'}}}]},primitive:{topology:'triangle-list',cullMode:'none'},depthStencil:{format:'depth24plus',depthWriteEnabled:true,depthCompare:'less'}};
    this.meshPipeline=await this.device.createRenderPipelineAsync(descriptor);this.glassPipeline=await this.device.createRenderPipelineAsync({...descriptor,depthStencil:{...descriptor.depthStencil,depthWriteEnabled:false}});
    for(const part of source){const data=[];const convert=v=>[v[0]/60,v[2]/60,v[1]/60];for(const ids of part.triangles){const [a,b,c]=ids.map(i=>convert(part.vertices[i]));const n=normalize(cross(sub(c,a),sub(b,a)));for(const v of [a,b,c])data.push(...v,...n)}const buffer=this.device.createBuffer({size:data.length*4,usage:GPUBufferUsage.VERTEX|GPUBufferUsage.COPY_DST});this.device.queue.writeBuffer(buffer,0,new Float32Array(data));const uniform=this.device.createBuffer({size:96,usage:GPUBufferUsage.UNIFORM|GPUBufferUsage.COPY_DST});const makeBind=p=>this.device.createBindGroup({layout:p.getBindGroupLayout(0),entries:[{binding:0,resource:{buffer:uniform}}]});this.meshes.push({...part,buffer,uniform,count:data.length/6,bind:makeBind(this.meshPipeline),glassBind:makeBind(this.glassPipeline)})}
    this.loadedCAD=true;return this.meshes.map(x=>x.name);
  }
  drawCAD(){const d=this.device,e=d.createCommandEncoder(),pass=e.beginRenderPass({colorAttachments:[{view:this.context.getCurrentTexture().createView(),loadOp:'clear',storeOp:'store',clearValue:{r:.024,g:.028,b:.045,a:1}}],depthStencilAttachment:{view:this.depth.createView(),depthLoadOp:'clear',depthStoreOp:'store',depthClearValue:1}});const p=this.params,cam=camera(p.yaw,p.pitch,p.zoom*(1+this.explode*.22),this.width/this.height);for(const part of [...this.meshes.filter(x=>x.opacity>=1),...this.meshes.filter(x=>x.opacity<1)]){if(this.hidden.has(part.name))continue;const exp=part.explode,v=new Float32Array(24);v.set(cam.matrix);v.set([exp[0]/60*this.explode,exp[2]/60*this.explode,exp[1]/60*this.explode,0],16);v.set([...part.color,part.opacity],20);if(part.name===this.selected)v.set([.9,.58,.20,1],20);d.queue.writeBuffer(part.uniform,0,v);const glass=part.opacity<1;pass.setPipeline(glass?this.glassPipeline:this.meshPipeline);pass.setBindGroup(0,glass?part.glassBind:part.bind);pass.setVertexBuffer(0,part.buffer);pass.draw(part.count)}pass.end();d.queue.submit([e.finish()])}
  drawFallback(){const ctx=this.ctx;if(!ctx)return;const w=this.canvas.width,h=this.canvas.height;ctx.fillStyle='#100b18';ctx.fillRect(0,0,w,h);const count=this.params.split?2:1;for(let n=0;n<count;n++){ctx.save();const width=w/count;ctx.translate(width*(n+.5),h*.53);const r=Math.min(width*.29,h*.27)/this.params.zoom;const grad=ctx.createRadialGradient(-r*.3,-r*.6,r*.02,0,-r*.2,r);grad.addColorStop(0,'#988bae');grad.addColorStop(.2,'#35264f');grad.addColorStop(.7,'#221436');grad.addColorStop(.92,'#554772');grad.addColorStop(1,'#b8a6d2');ctx.fillStyle=grad;ctx.beginPath();ctx.arc(0,-r*.2,r,0,Math.PI*2);ctx.fill();ctx.save();ctx.beginPath();ctx.arc(0,-r*.2,r*.95,0,Math.PI*2);ctx.clip();if(this.params.art){for(let i=0;i<14;i++){const a=i*2.39+(this.time||0)*.06,x=Math.sin(a)*r*.48,y=-r*.2+Math.cos(a*1.3)*r*.55,g=ctx.createRadialGradient(x,y,0,x,y,r*.6);g.addColorStop(0,`rgba(146,61,240,${.11*this.params.glow})`);g.addColorStop(1,'rgba(86,12,170,0)');ctx.fillStyle=g;ctx.fillRect(-r,-r*1.3,r*2,r*2.3)}}ctx.restore();const b=ctx.createLinearGradient(-r,0,r,0);b.addColorStop(0,'#09090b');b.addColorStop(.3,'#3b3030');b.addColorStop(.6,'#111016');b.addColorStop(1,'#060608');ctx.fillStyle=b;ctx.beginPath();ctx.moveTo(-r*.83,r*.66);ctx.lineTo(-r*1.1,r*1.35);ctx.quadraticCurveTo(0,r*1.65,r*1.1,r*1.35);ctx.lineTo(r*.83,r*.66);ctx.fill();ctx.strokeStyle='#8b672e';ctx.lineWidth=r*.022;for(const y of [.73,1.34]){ctx.beginPath();ctx.ellipse(0,r*y,r*(y===.73?.87:1.1),r*.13,0,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#b8944f';ctx.textAlign='center';ctx.font=`${r*.37}px Georgia`;ctx.fillText('✧  ☾  ✦',0,r*1.18);ctx.strokeStyle='#b377ff';ctx.shadowColor='#8539ee';ctx.shadowBlur=r*.13;ctx.lineWidth=r*.025;ctx.beginPath();ctx.ellipse(0,r*.68,r*.78,r*.10,0,0,Math.PI*2);ctx.stroke();ctx.restore()}}
  dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.observer.disconnect();this.depth?.destroy();this.uniform?.destroy();for(const m of this.meshes){m.buffer.destroy();m.uniform.destroy()}this.device?.destroy()}
}
